### ISSUE TITLE
Necesita ajustes

### ISSUE THREAD

**Issue by alexbalieiro** [leandromartin114/dwf-m7-desafio#1]
Hola Leandro, estuve testeando la app, tiene algunas comportamientos extraños a nivel estético como el siguiente donde queda fuera de lugar el btn hambuerguesa con su menú:

![Captura de pantalla de 2022-08-06 12-10-05](https://user-images.githubusercontent.com/74037904/183255128-d3a8e52d-71f7-450f-8ced-1013de1aeda5.png)

![Captura de pantalla de 2022-08-06 12-15-57](https://user-images.githubusercontent.com/74037904/183255167-e9c9a7a7-a116-40d8-b792-9da0c282d81b.png)

Y también al querer reportar una mascota, la pantalla te da el mensaje de reporte exitoso pero en la consola marca un error 400 y cuando entras al menú de "Mis mascotas reportadas" no figura el reporte:

![Captura de pantalla de 2022-08-06 12-25-42](https://user-images.githubusercontent.com/74037904/183255449-1427b968-6fab-40fb-967e-57001e73712c.png)

Revisa esas cuestiones para que pueda ser aprobado el desafío, lo demás está muy bien logrado, sobre todo las animaciones, se nota que le dedicaste mucho tiempo, a meterle!

**Comment by leandromartin114** [comment]
Hola Alex, muchas gracias por tu devolución! Creo haber solucionado los inconvenientes. Algunas propiedades css que faltaban en cuanto a la estética y el problema al reportar una mascota se daba por un error en unas de las env var de cloudinary en heroku.
