### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by FerDR89** [leandromartin114/dwf-m7-desafio#2]
Buenas Leandro,
Te paso lo que vi de la app que necesitaría ajustarse:

Acá el maker del mapbox me lo manda hacia abajo:

![image](https://user-images.githubusercontent.com/74626765/183412234-9f35ecfc-08ac-438d-b55b-ee6fff773236.png)

Fíjate eso y volve a mandarlo.
Éxitos en el próximo modulo, muy buen desafió!

**Comment by leandromartin114** [comment]
Hola Fer! Muchas gracias por la devolución! Ya pude corregir esto de los marcadores.
![Screenshot_2](https://user-images.githubusercontent.com/84253648/183492111-d7d585cf-508f-4b93-b6eb-5543b63c8e5c.jpg)
