### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by amunozdev** [leandromartin114/dwf-m7-desafio#3]
Buenas Leandro, felicitaciones por terminar el desafío, muy bueno tu laburo, hay un par de cositas que se podrían mejorar:

Cuando creas un usuario, se puede crear el mismo sin que las contraseñas coincidan:
![Captura desde 2022-08-10 11-27-39](https://user-images.githubusercontent.com/77214476/183932670-7a323023-df2a-4dd7-88e3-b51ecb4a31a2.png)

Se puede crear una mascota perdida sin llenar ninguno de los campos:
![Captura desde 2022-08-10 11-47-58](https://user-images.githubusercontent.com/77214476/183933441-4b3a90f8-bea2-4980-a13a-8b99d3cd6ce1.png)
Lo mismo pasa cuando reportas info de una mascota, estaría bueno recibir algún tipo de alerta diciendo que no se puede enviar un reporte vacío

Cuando cerras sesión, la data sigue de usuario sigue quedando en el localStorage, estaría bueno removerla.

En cuánto a los endpoints vi que usaste then/catch en casi todos y está perfecto, pero pienso que con async/await queda más legible:
![Captura desde 2022-08-10 12-06-07](https://user-images.githubusercontent.com/77214476/183947210-6eaa19b1-7b9d-4789-a876-ec0fe45840e7.png)

Con async/await:
![Captura desde 2022-08-10 12-05-43](https://user-images.githubusercontent.com/77214476/183947414-ffabe8c3-7799-4c02-82d5-72b0c11f5a6e.png)

De todas maneras esos endpoints están excelente, ya que solo reciben un request, devuelven una respuesta y nada más 👌

En report-controllers.ts pienso que estaria bueno sacar esta logica del controller y meterla en una funcion que se encuentre en la lib:
![Captura desde 2022-08-10 13-34-30](https://user-images.githubusercontent.com/77214476/183964705-fc64af1b-9121-4d82-a4b9-442eedf98006.png)

En general estaría bueno que uses más async/await, con el tiempo te vas a dar cuenta de que es más sencillo y legible, también estaría bueno que hagas más uso de TypeScript, sobre todo en el back, te va a sumar muchísimo a la hora de exponer el proyecto en una entrevista y o si alguien lo mira.

Más allá de esos detalles veo todo bastante prolijo y organizado y se nota que le metiste horas, éxitos en el próximo módulo!!

**Comment by leandromartin114** [comment]
Hola Alex, muchísimas gracias por esta devolución! Me suma un montón, sobre todo para este nuevo módulo que seguimos con la misma app de mascotas y ya tengo varias cosas para mejorarla. Saludos.
